name: uic_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.1

  # Bloc cached clear helper
  bloc_concurrency: ^0.2.0

  # Dependency Injection
  get_it: ^7.2.0

  # shimmer
  shimmer: ^2.0.0

  # Network
  graphql_flutter: ^5.1.2

  # Network check
  internet_connection_checker: ^1.0.0+1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Json
  json_serializable: ^6.6.0

  # Value equality
  equatable: ^2.0.3

  # Others
  dartz: ^0.10.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

